### ISSUE TITLE
not_to(equal) using == and not !=

### ISSUE THREAD

**Issue by alejandrodob** [jaimegildesagredo/expects#39]
When using the matcher equal with a not, (e.g `expect(some_object).not_to(equal(another_object))` first the equal is performed with the `==` operator and then the result is operated with a boolean not. Internally this will call the `__eq__` method on the object to perform the comparison. However, when comparing two objects for inequality in Python with the `!=` operator, the method that will be called is `__ne__`. For most of the cases, this is ok, as `__ne__` will probably be calling `__eq__` (or maybe not, but anyway `not ==` should be equivalent to `!=` if the world made sense at all!).

This is not a big deal by itself, but sometimes one would expect a different behaviour of `not_to(equal())` than the current one. For example, if you're TDDing the `__eq__` and `__ne__` methods of a class (this just happened to me :D).

I am not sure whether making `not_to(equal)` use the `!=` operator would be easy to implement or even would make sense at all but, if not, maybe having another matcher called `different` or `unequal` that actually performed the comparison with `!=` could fit.

If you think this could be of some value I would be glad to help implementing it.

Anyway, I would like to thank you for this great library!

**Comment by jaimegildesagredo** [comment]
Hi @alejandrodob, what a good catch! :)

I definitely think it makes a lot of sense and also could be easily implemented.

We can use the [_match_negated](http://expects.readthedocs.org/en/v0.8.0rc1/custom-matchers.html#expects.matchers.Matcher._match_negated) method to implement custom negated behavior for matchers.

If you want you could open a pull request for this change (you can take a look to other examples already in the code: [the have_keys matcher](https://github.com/jaimegildesagredo/expects/blob/master/expects/matchers/built_in/have_keys.py#L56)) and could be released as 0.8.0rc3 since it could be considered a bug in the equal matcher.

Let me know if you need some help, and thank you so much for using expects and taking the time to improve it. I really appreciate it :)

**Comment by alejandrodob** [comment]
Hi @jaimegildesagredo,

I've worked on a couple of versions. The implementation is actually the same (and in fact very simple as you said), but the tests are different. In [this version](https://github.com/alejandrodob/expects/tree/not-equal-strict-comparison-support) I've added the tests in a different context, also making them very explicit. I do not like about them that they're a bit out of the line of the rest of the tests, as they are not really describing a spec, but an implementation detail maybe (by spying on the call to the `__eq__` method). On the other hand, [here](https://github.com/alejandrodob/expects/tree/not-equal-strict-comparison-support-v2) I've tried to keep the same existing tests, but instead of comparing numbers, compare instances of a class with a "special" `__eq__` behaviour so it fails for some special cases, thus making it easy to catch the bug for those special cases when using `not_to(equal)`.

I think that this second version, despite being a bit trickier, is more in the spirit of the rest of the project tests.

Please, take a look at both and tell me what you think, if you prefer any of them or they're both crazy :)

**Comment by jaimegildesagredo** [comment]
Hi @alejandrodob and sorry for the delay (I was out for a few days), and thank you again for your great work.

I like the second option but I think it would be better to maintain the previous tests (comparing simple numbers) and just add a new case for an object with a custom `__ne__` method. I think this way the tests would be a little simpler and more clear.

When you have it just open a pull request and I'll merge it ASAP :smile:

Thank you!
