### ISSUE TITLE
be_a is failing with imported class because of Path

### ISSUE THREAD

**Issue by pedroadame** [jaimegildesagredo/expects#64]
Hi!

In a code like this
```py
from src.folder.file import MyClass

with description('my description'):
    with it('my test'):
        obj = MyClass()
        expect(obj).to(be_a(MyClass))
```

is failing with the following error:

`Expected <src.folder.file.MyClass> to be <MyClass>`

Is this some sort of bug? How we deal with this?

**Comment by jaimegildesagredo** [comment]
Hi Pedro!

Thanks for opening this issue describing the error you found.

The code on the example should work since it looks the same as [this test](https://github.com/jaimegildesagredo/expects/blob/master/specs/matchers/built_in/be_a_spec.py#L10-L14), and the `be_a` matcher only relies on the Python `isinstance` built-in function.

So the source of the problem probably is on another detail of your code or environment. One option is you are [importing "MyClass" from two different sources](https://stackoverflow.com/questions/46708659/isinstance-fails-for-a-type-imported-via-package-and-from-the-same-module-direct).
